"""drop email from users

Revision ID: 2b9342a51468
Revises: d8547a72f5aa
Create Date: 2026-09-14 11:17:30.443180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9342a51468'
down_revision = 'd8547a72f5aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)

    # ### end Alembic commands ###
